fire_sale/checkout/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='checkout'),
    path('<int:order_id>', views.register_checkout, name="register-checkout"),
    path('<int:order_id>/payment', views.register_checkout_payment, name="register-checkout-payment"),
    path('<int:checkout_id>/preview', views.get_checkout_by_id, name="preview"),
    path('<int:checkout_id>/confirm', views.checkout_complete, name="confirm-checkout"),
    path("<int:checkout_id>/review", views.user_review, name="review")
]

fire_sale/fire_sale/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('item.urls')),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('user/', include('user.urls')),
    path('message/', include('message.urls')),
    path('checkout/', include('checkout.urls')),
]

fire_sale/item/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='item-index'),
    path('create', views.create, name='item-create'),
    path('<int:item_key>', views.get_item_by_id),
    path('<int:item_key>/edit', views.edit, name='item-edit'),
    path('<int:item_key>/bid', views.bid, name='item-bid'),
    path('<int:item_key>/offers', views.offers, name='item-bid'),
    path('<int:item_key>/delete', views.delete, name='delete-item'),
    path('offer/<int:offer_id>/accept', views.accept_item_bid, name='offer-accept'),
    path('<int:item_key>/similar', views.similar, name='similar-items'),
    path('<int:item_key>/addimage', views.addimage, name='item-addimage'),
    path('<int:item_key>/<int:image_key>/removeimage', views.removeimage, name='item-removeimage'),
]

fire_sale/item/models.py
from django.db import models
from django.utils import timezone
from user.models import User
from django.db import connection


# Create your models here.
def dictfetchall(cursor):
    """ Return all rows from a cursor as a dict """
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


class ItemSalesType(models.Model):
    name = models.CharField(max_length=200)
    buyItNow = models.BooleanField(default=False)
    auction = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class ItemCondition(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class ItemCategory(models.Model):
    name = models.CharField(max_length=200)
    icon = models.CharField(max_length=200, blank=True)
    order = models.IntegerField(default=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(ItemCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    @property
    def count(self):
        return self.category.item_set.filter(show_in_catalog=True,
                                             has_accepted_offer=False,
                                             tags__name__contains=self.name).count()


class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sale_type = models.ForeignKey(ItemSalesType, on_delete=models.CASCADE)
    price_minimum = models.FloatField(default=0)
    price_fixed = models.FloatField(null=True, blank=True)
    condition = models.ForeignKey(ItemCondition, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=10000)
    show_in_catalog = models.BooleanField(default=True)
    date_ends = models.DateTimeField(null=True, blank=True)
    created = models.DateTimeField(default=timezone.now)
    edited = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(ItemCategory, on_delete=models.CASCADE)
    hitcount = models.IntegerField(default=0)
    has_accepted_offer = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True, default=None)

    class Meta:
        indexes = [
            models.Index(fields=['show_in_catalog', '-hitcount', 'name'], name="item_main_view_index"),
        ]

    def __str__(self):
        res = self.name
        if not self.show_in_catalog:
            res += ' (unlisted)'
        res += ' [' + self.user.username + ']'
        return res

    def current_price(self):
        if self.offer_set.count() > 0:
            highest = self.offer_set.order_by('-amount').first().amount
            if highest > self.price_minimum:
                return highest
        return self.price_minimum

    def number_of_offers(self):
        return self.offer_set.count()

    def current_winning_user(self):
        if self.offer_set.count() > 0:
            highest = self.offer_set.order_by('-amount').first()
            if highest.amount > self.price_minimum:
                return highest.offer_by
        return None

    def current_winning_user_id(self):
        winner = self.current_winning_user()
        if winner is not None:
            return winner.id
        return None

    def sort_order(self):
        """
            gets alternate sort orders for items
        :return: array of sort orders
        """
        # popd = Item.objects.filter(hitcount__lte=self.hitcount).count()
        # popa = Item.objects.filter(hitcount__gte=self.hitcount).count()
        # pricea = Item.objects.filter(price_minimum__lte=self.price_minimum).count()
        # priced = Item.objects.filter(price_minimum__gte=self.price_minimum).count()
        # alpha = Item.objects.filter(name__lte=self.name).count()
        # alphd = Item.objects.filter(name__gte=self.name).count()

        # Þessi with skipun gerir það sama og allar .count() skipanirnar fyrir ofan, nema í einu kalli ístaðin fyrir 6
        with connection.cursor() as cursor:
            cursor.execute('select ' +
                           '(SELECT count(*) FROM "item_item" WHERE "item_item"."hitcount" >= ' +
                           str(self.hitcount) + ') as popa, ' +
                           '(SELECT count(*) FROM "item_item" WHERE "item_item"."hitcount" < ' +
                           str(self.hitcount) + ') as popd, ' +
                           '(SELECT count(*) FROM "item_item" WHERE "item_item"."price_minimum" >= ' +
                           str(round(self.price_minimum)) + ') as priced, ' +
                           '(SELECT count(*) FROM "item_item" WHERE "item_item"."price_minimum" < ' +
                           str(round(self.price_minimum)) + ') as pricea, ' +
                           '(SELECT count(*) FROM "item_item" WHERE "item_item"."name" >= \'' +
                           self.name + '\') as alphd, ' +
                           '(SELECT count(*) FROM "item_item" WHERE "item_item"."name" < \'' +
                           self.name + '\') as alpha ' +
                           '')
            return dictfetchall(cursor)[0]

        orderlist = {"popa": popa, "popd": popd, "alpha": alpha, "alphd": alphd, "pricea": pricea, "priced": priced}
        return orderlist


class ItemImage(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    url = models.CharField(max_length=10000)
    description = models.CharField(max_length=10000, blank=True)

    def __str__(self):
        res = f'Image {self.id} for {self.item.name}'
        return res


class Offer(models.Model):
    offer_by = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    amount = models.FloatField(default=0)
    accepted = models.BooleanField(default=False)
    valid = models.BooleanField(default=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.offer_by.first_name + ' wants ' + self.item.name + ' for ' + f'{self.amount:.0f}'

    def __int__(self):
        return round(self.amount)

    def get_highest_by_user(self, user):
        """
            A short explination of what this SQL command does. We are trying to get information 
            on my current bid status on an item :
                item ID
                number of my bids on item
                my highest bid
                # the current highest bid
                # highest bid user ID                
        """
        with connection.cursor() as cursor:
            cursor.execute('select max(o.amount) as "myMax", i.id, i.name, count(*) as "bids"' +
                           'from item_offer o ' +
                           'join item_item i on i.id = o.item_id ' +
                           'where o.offer_by_id = ' + str(user.id) + 'and o.item_id = ' +
                           str(self.item.id) + ' and o.amount >= i.price_minimum ' +
                           'group by i.id, o.item_id')
            return dictfetchall(cursor)
        return None

fire_sale/checkout/forms/checkout_form.py
from django.forms import ModelForm, widgets
from ..models import Checkout, UserReview


class CheckoutForm(ModelForm):
    class Meta:
        model = Checkout
        exclude = []
        widgets = {
            'offer': widgets.HiddenInput(attrs={'class': 'd-none'}),
            'shipping_name': widgets.TextInput(attrs={'class': 'form-control'}),
            'street_address': widgets.TextInput(attrs={'class': 'form-control'}),
            'house_number': widgets.TextInput(attrs={'class': 'form-control'}),
            'city': widgets.TextInput(attrs={'class': 'form-control'}),
            'country': widgets.Select(attrs={'class': 'form-control'}),
            'postal_code': widgets.TextInput(attrs={'class': 'form-control'}),
            'credit_card_holder': widgets.TextInput(attrs={'class': 'form-control'}),
            'expiration_month': widgets.Select(attrs={'class': 'form-control'}),
            'expiration_year': widgets.Select(attrs={'class': 'form-control'}),
            'credit_card_number': widgets.NumberInput(attrs={'class': 'form-control'}),
            'cvv': widgets.NumberInput(attrs={'class': 'form-control'}),

        }


class UserReviewForm(ModelForm):

    class Meta:
        model = UserReview
        fields = ['checkout', 'seller', 'review_text', 'rating']
        labels = {
            'review_text': 'Your review:',
            'rating': 'Your rating:'
        }
        widgets = {
            'checkout': widgets.HiddenInput(attrs={'class': 'd-none' }),
            'seller': widgets.HiddenInput(attrs={'class': 'd-none'}),
            'review_text': widgets.Textarea(attrs={'class': 'form-control'}),
            'rating': widgets.Select(attrs={'class': 'form-control'})
        }
        help_texts = {
            'review_text': 'Please write your review here...'
        }

fire_sale/checkout/views.py
from django.contrib.auth.decorators import login_required
from checkout.forms.checkout_form import CheckoutForm, UserReviewForm
from message.forms.msg_form import MsgReplyForm
from django.shortcuts import render, redirect, get_object_or_404
from checkout.models import Checkout, get_year_choice
from item.models import Offer


# Create your views here.
@login_required
def index(request, order_id):
    current_user = request.user
    order = get_object_or_404(Offer, pk=order_id)
    return render(request, "checkout/index.html", {
        "Checkout": Checkout.objects.filter(name=current_user.id),
        'order': order
    })


def mask_card(card):
    return str(card)[0:2] + '** **** **** ' + str(card)[-4:]


@login_required
def get_checkout_by_id(request, checkout_id):
    months = dict(Checkout.MONTH_CHOICE)
    years = dict(get_year_choice())
    checkout = [{
        "id": co_entry.id,
        "checkout_id": checkout_id,
        "offer_id": co_entry.offer_id,
        "Full Shipping Name:": co_entry.shipping_name,
        "Street Address:": co_entry.street_address,
        "House Number:": co_entry.house_number,
        "City:": co_entry.city,
        "Country:": co_entry.country,
        "Postal Code:": co_entry.postal_code,
        "Credit card holder:": co_entry.credit_card_holder,
        "Credit card number:": mask_card(co_entry.credit_card_number),
        "Expiration month:": months[co_entry.expiration_month],
        "Expiration year:": years[co_entry.expiration_year],
        "CVV:": co_entry.cvv,
        # "is_confirmed": co_entry.is_confirmed
    } for co_entry in Checkout.objects.filter(pk=checkout_id)]
    return render(request, 'checkout/preview.html', {"checkout": checkout})


@login_required
def register_checkout(request, order_id):
    order = get_object_or_404(Offer, pk=order_id)
    checkout = Checkout.objects.filter(offer_id=order_id).first()
    if order.offer_by != request.user:
        return redirect('my-profile')

    if request.method == 'POST':
        form_data = request.POST.copy()
        form_data['offer'] = order.id
        form = CheckoutForm(instance=checkout, data=form_data)
        if form.is_valid():
            form.save()
            checkout = Checkout.objects.filter(offer_id=order_id).first()
            return redirect('preview', checkout_id=checkout.id)
    checkoutForm = CheckoutForm(instance=checkout)
    return render(request, 'checkout/index.html', {
        'form': checkoutForm,
        'order': order,
        'payment': 0,
    })


@login_required
def register_checkout_payment(request, order_id):
    order = get_object_or_404(Offer, pk=order_id)
    checkout = Checkout.objects.filter(offer_id=order_id).first()
    if order.offer_by != request.user:
        return redirect('my-profile')

    if request.method == 'POST':
        form_data = request.POST.copy()
        form_data['offer'] = order.id
        form = CheckoutForm(instance=checkout, data=form_data)
        if form.is_valid():
            form.save()
            checkout = Checkout.objects.filter(offer_id=order_id).first()
            return redirect('preview', checkout_id=checkout.id)
    checkoutForm = CheckoutForm(instance=checkout)
    return render(request, 'checkout/index.html', {
        'form': checkoutForm,
        'order': order,
        'payment': 1,
    })


@login_required
def checkout_complete(request, checkout_id):
    checkout = get_object_or_404(Checkout, pk=checkout_id)
    if checkout.offer.offer_by != request.user:
        return redirect('my-profile')

    if checkout.is_confirmed:
        return redirect('review', checkout_id=checkout_id)

    # save that checkout is completed
    checkout.is_confirmed = True
    checkout.save()

    # send message to seller and buyer about successful checkout
    form_msg = MsgReplyForm(data={'sender': request.user,
                                  'receiver': checkout.offer.item.user,
                                  'item': checkout.offer.item,
                                  'offer': checkout.offer,
                                  'msg_subject': 'Payment completed',
                                  'msg_body': 'Ship \'' + checkout.offer.item.name + '\' to: ' +
                                  checkout.offer.offer_by.first_name + ' ' + checkout.offer.offer_by.last_name + ', ' +
                                  checkout.street_address + ' ' + checkout.house_number + ', ' +
                                  checkout.postal_code + ' ' + checkout.city + ', ' +
                                  checkout.country.countryName+' '
                                  })
    if form_msg.is_valid():
        form_msg.save()

    form_msg = MsgReplyForm(data={'sender': checkout.offer.item.user,
                                  'receiver': request.user,
                                  'item': checkout.offer.item,
                                  'offer': checkout.offer,
                                  'msg_subject': 'Shipment processing has started',
                                  'msg_body': 'We are preparing to ship \'' + checkout.offer.item.name + '\' to: ' +
                                  checkout.offer.offer_by.first_name + ' ' + checkout.offer.offer_by.last_name + ', ' +
                                  checkout.street_address + ' ' + checkout.house_number + ', ' +
                                  checkout.postal_code + ' ' + checkout.city + ', ' +
                                  checkout.country.countryName+' '
                                  })
    if form_msg.is_valid():
        form_msg.save()

    # redirect to review site
    return redirect('review', checkout_id=checkout_id)


@login_required
def user_review(request, checkout_id):
    checkout = get_object_or_404(Checkout, pk=checkout_id)
    if request.method == "POST":
        form = UserReviewForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    seller = checkout.offer.item.user
    buyer = checkout.offer.offer_by.get_full_name()
    item = checkout.offer.item
    form = UserReviewForm(initial={'checkout': checkout, 'seller': seller})
    return render(request, "checkout/user_review.html", {
        "form": form,
        "seller": seller.get_full_name(),
        "buyer": buyer,
        "item": item,
        "checkout_id": checkout_id
    })

fire_sale/templates/checkout/index.html
{% extends 'base.html' %}
{% block content %}

    <div class="container_checkout">
        <div class="checkout">
            <div class="child">
            <h2>Fire Sales Awesome Express Checkout - Review Your Cart Items </h2>
                <div class="item_checkout p-3 border rounded">
                    <img class="p-1 rounded shadow img_checkout w-25"  src="{{ order.item.itemimage_set.first.url }}"
                         alt="{{ order.item.itemimage_set.first.description }}"/>
                    <p class="order_price"> <br>{{ order.amount|floatformat:'-2g' }} kr</p>
                    <h3 > {{ order.item.name }} </h3>

                    </div>
            </div>
            <form class="final_info" method="post">
                {% csrf_token %}
                {{ form.errors }}
                <div id="checkoutShipping" class="address border-top border-success mt-5">
                    <h4>Shipping Address</h4>
                    <p>Full Name{{ form.shipping_name }}</p>
                    <p>Street Address{{ form.street_address }}</p>
                    <p> House Number{{ form.house_number }}</p>
                    <p>City {{ form.city }}</p>
                    <p> Country {{ form.country }}</p>
                    <p>Postal code {{ form.postal_code }}</p>
                    <button type="button" class="btn btn-success" onclick="$('#checkoutPayment').show();$('#checkoutShipping').hide();$('#checkoutProceed').show();">To payment information</button>
                </div>


                <div id="checkoutPayment" class="payment border-top border-success mt-5" style="display:none">
                    <h4>Payment method </h4>
                    <p>Credit card holder{{ form.credit_card_holder }}</p>
                    <p>Credit card number{{ form.credit_card_number }}</p>
                    <p> Expiration Month{{ form.expiration_month }}</p>
                    <p>Expiration Year {{ form.expiration_year }}</p>
                    <p> CVV {{ form.cvv }}</p>
                    <button type="button" class="btn btn-success" onclick="$('#checkoutPayment').hide();$('#checkoutShipping').show();$('#checkoutProceed').hide();">Back to shipping information</button>
                </div>

                <br/>
                <input type="submit" class="btn btn-lg btn-warning rounded" value="Proceed" id="checkoutProceed" style="display:none">
            </form>
        </div>
    </div>
    </div>
    <br/><br/>
    {% if payment == 1 %}
    <script>
        $('#checkoutPayment').show();
        $('#checkoutShipping').hide();
        $('#checkoutProceed').show();
    </script>
    {% endif %}
{% endblock %}

fire_sale/templates/checkout/index_new.html
{% extends 'base.html' %}
{%load widget_tweaks%}
{% block content %}

 <div class="container">

    <div class="col">
        <h2>Review Your Cart Items </h2>
        <img class="p-1 rounded shadow img_checkout" width="140" src="{{ order.item.itemimage_set.first.url}}" alt="{{ order.item.itemimage_set.first.description }}" />
        <p class="order_item"> {{ order.item }} </p>
        <p class="order_price">{{ order.amount|floatformat:'-2g' }} kr</p>
    </div>
      <form method="POST" class="container">
          <div class="form-row">
            <div class="col-md-6">
                {% render_field form.street_address placeholder=form.street_address.label class="form-control" %}
                {% render_field form.house_number placeholder=form.house_number.label %}
                {% render_field form.city placeholder=form.city.label %}
                {% render_field form.country placeholder=form.country.label %}
                {% render_field form.postal_code placeholder=form.postal_code.label %}

            </div>
            <div class="col-md-6">
                {% render_field form.credit_card_holder placeholder=form.credit_card_holder.label %}
                {% render_field form.credit_card_number placeholder=form.credit_card_number.label %}
                {% render_field form.expiration_month placeholder=form.expiration_month.label %}
                {% render_field form.postal_code placeholder=form.postal_code.label %}
                {% render_field form.cvv placeholder=form.cvv.label %}
            </div>
          </div>
        </form>


      <div class="row"><input type="submit" class="btn_create rounded" value="Proceed"></div>
</div>

{% endblock %}

fire_sale/templates/checkout/preview.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Review your order - you are about to complete the purchase</h2>
        {% for entry in checkout %}
            {% for key,value in entry.items %}
                {% if key != "id" and key != "offer_id" and key != "checkout_id" %}
                    <ul class="list-group list-group-horizontal-sm">
                        <li class="list-group-item preview-first">{{ key }}</li>
                        <li class="list-group-item flex-fill">{{ value }}</li>
                    </ul>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </div>
    <footer aria-label="preview footer">
        <div class="container p-4">
            {% for entry in checkout %}
                <a class="btn btn-primary" href="{% url "register-checkout" order_id=entry.offer_id %}">
                    Edit the shipping information
                </a>
                <a class="btn btn-primary" href="{% url "register-checkout-payment" order_id=entry.offer_id %}">
                    Edit the payment information
                </a>
                <a class="btn btn-danger" href="{% url "my-profile" %}">Cancel order</a>
                <a class="btn btn-success btn-lg" href="{% url "confirm-checkout" checkout_id=entry.checkout_id %}">Confirm</a>
            {% endfor %}

        </div>
    </footer>
{% endblock %}

fire_sale/templates/checkout/user_review.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container">
<h1>User Review</h1>
    <h4>
        Congratulations {{ buyer }}!
    </h4>
    <p>
        You have just bought and completed the purchase of <b>{{ item.name }}</b> from <b>{{ seller }}</b>.
        Please tell {{ seller }} how pleased you are with your purchase and add a rating as
        I know {{ seller }} will very much appreciate it!
    </p>
    <form action="/checkout/{{ checkout_id }}/review" method="post">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% if field is form.review_text %}
                {% render_field form.review_text placeholder=form.review_text.help_text %}
            {%  endif %}
            {% if field is form.rating %}
                {% render_field form.rating  %}
            {%  endif %}
            {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        {% endfor %}
      <div class="form-group">
        <button type="submit" class="btn btn-success">
             Submit
        </button>
          <button type="submit" class="btn btn-default">
             Skip
        </button>
    </div>

    </form>
</div>
{% endblock %}